### PR TITLE
Make AnyOf not fail if nothing is evaluated

### LINKED ISSUE #138: AnyOf Operator should not fail if no Expressions were evaluated
If all Expressions defined in an AnyOf operator are skipped due to not finding relevant scopes (i.e. wildcard in path not matching anything, resource type not found), the AnyOf operator should "pass" with no results.

Currently, AnyOf fails in this scenario.

### PR DESCRIPTION
**Pull request by JohnathonMohr**
Updates AnyOf operator to only fail if something was evaluated and something internal failed.  Otherwise, if nothing is evaluated, pass by default.  This ensures rules in which no paths/resource types are relevant inside an AnyOf don't result in a failure.  Closes #138.

- Update AnyOf with bug fix
- Update corresponding test for AnyOf and AllOf

### CODE REVIEW

File: src/Analyzer.JsonRuleEngine/Expressions/AnyOfExpression.cs [hunk 1]
```diff
@@ -48,11 +47,10 @@ public override JsonRuleEvaluation Evaluate(IJsonPathResolver jsonScope)
                     // Add evaluations if scopes were found to evaluate
                     if (evaluation.HasResults)
                     {
-                        evaluationPassed |= evaluation.Passed;
                         jsonRuleEvaluations.Add(evaluation);
                     }
                 }
-
+                bool evaluationPassed = jsonRuleEvaluations.Count == 0 || !jsonRuleEvaluations.TrueForAll(e => !e.Passed);
```
Comment (VeraBE) [inline src/Analyzer.JsonRuleEngine/Expressions/AnyOfExpression.cs:53]:
```suggestion
                bool evaluationPassed = jsonRuleEvaluations.Count == 0 || jsonRuleEvaluations.Any(e => e.Passed);
```

**Review by yane3628 — APPROVED** [review]

**Review by VeraBE — APPROVED** [review]
