### PR TITLE
Fix possible stack overflow exception in line number mapping

### LINKED ISSUE #212: Stack Overflow exception can occur on templates with resource copies
When there are rule violations found in templates that have copied resources from template copy-loops, an infinite recursion happens when trying to map the identified line number from the expanded template to the original.  The cause is related to the resources getting reordered when the copies are created (the original resource is moved to the end along with its copies).

### PR DESCRIPTION
**Pull request by JohnathonMohr**
## Description

When a template contains copy loops, resources get moved around when the copies are created during parsing.  When this happens, it could trigger a bug that results in a stack overflow exception when trying to do line number mapping.  This fixes the line number mapping implementation.   (Fixes #212)

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] **I have read the [contribution guidelines](../CONTRIBUTING.md).**
- [x] The pull request does not introduce breaking changes.

### [General Guidelines](../CONTRIBUTING.md)
- [x] Title of the pull request is clear and informative.
- [x] Description of the pull request is clear and informative.
- [x] I have added myself to the 'assignees'.
- [x] I have added 'linked issues' if relevant.

### [Testing Guidelines](../CONTRIBUTING.md#tests)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by anaismiller — APPROVED** [review]

File: src/Analyzer.Utilities.UnitTests/JsonLineNumberResolverTests.cs [hunk 1]
```diff
@@ -213,14 +231,16 @@ public class JsonLineNumberResolverTests
...
             new object[] { "parameters.parameter1.maxValue", new object[] { "parameters", "parameter1" }, "Beginning of path matches original template parameters, but has missing property" },
             new object[] { "resources[0].anExpandedProperty", new object[] { "resources", 0 }, "Beginning of path matches original template resources array, but has missing property" },
-            new object[] { "resources[4].properties.anotherProperty", new object[] { "resources", 0, "properties", "anotherProperty" }, "Path is in a copied resource" },
-            new object[] { "resources[4].properties.missingProperty", new object[] { "resources", 0, "properties" }, "Path is in a copied resource and has missing property" },
+            new object[] { "resources[4].properties.anotherProperty", new object[] { "resources", 1, "properties", "anotherProperty" }, "Path is in a moved (original from copy loop) resource" },
+            new object[] { "resources[5].properties.anotherProperty", new object[] { "resources", 1, "properties", "anotherProperty" }, "Path is in a new (copied) resource" },
```
Comment (yane3628) [inline src/Analyzer.Utilities.UnitTests/JsonLineNumberResolverTests.cs:235]:
```suggestion
            new object[] { "resources[5].properties.anotherProperty", new object[] { "resources", 1, "properties", "anotherProperty" }, "Path is in a new (copied/duplicated) resource" },
```

Comment (yane3628) [reply src/Analyzer.Utilities.UnitTests/JsonLineNumberResolverTests.cs:235]: I'm thinking it may be clearer if we use the word duplicated to distinguish from _original_ and _duplicate_ copy of the _copy_ resource since we refer to the concept as "copy resources" and we refer to copies when we embed them as a sub-resource too.

File: src/Analyzer.Utilities.UnitTests/JsonLineNumberResolverTests.cs [hunk 2]
```diff
@@ -213,14 +231,16 @@ public class JsonLineNumberResolverTests
...
+            new object[] { "resources[5].properties.missingProperty", new object[] { "resources", 1, "properties" }, "Path is in a copied resource and has missing property" },
```
Comment (yane3628) [inline src/Analyzer.Utilities.UnitTests/JsonLineNumberResolverTests.cs:236]:
```suggestion
            new object[] { "resources[5].properties.missingProperty", new object[] { "resources", 1, "properties" }, "Path is in a duplicated resource and has missing property" },
```

File: src/Analyzer.Utilities.UnitTests/JsonLineNumberResolverTests.cs [hunk 3]
```diff
@@ -213,14 +231,16 @@ public class JsonLineNumberResolverTests
...
+            new object[] { "resources[4].properties.missingProperty", new object[] { "resources", 1, "properties" }, "Path is in a moved resource from copying and has missing property" },
```
Comment (yane3628) [inline src/Analyzer.Utilities.UnitTests/JsonLineNumberResolverTests.cs:237]:
```suggestion
            new object[] { "resources[4].properties.missingProperty", new object[] { "resources", 1, "properties" }, "Path is in a reordered resource from copying and has missing property" },
```

**Review by yane3628 — APPROVED** [review]

File: src/Analyzer.Utilities.UnitTests/JsonLineNumberResolverTests.cs (hunk 1 above)
Comment (JohnathonMohr) [reply src/Analyzer.Utilities.UnitTests/JsonLineNumberResolverTests.cs]: Good suggestion :)
