### PR TITLE
Fix null reference exception in Regex operator

### LINKED ISSUE #101: Regex operator throws exception when evaluating undefined property
Regex has the same issue Equals did.  Details in issue #99.

### PR DESCRIPTION
**Pull request by yane3628**
Fix null reference exception in Regex operator (Closes #101)

### CODE REVIEW

File: src/Analyzer.JsonRuleEngine.UnitTests/RegexOperatorTests.cs [hunk 1]
```diff
@@ -47,14 +47,29 @@ public void EvaluateExpression_PropertyIsNotString_EvaluationIsFalse(object obje
...
             var regexOperator = new RegexOperator("[");
             regexOperator.EvaluateExpression(TestUtilities.ToJToken("someValue"));
         }
 
+        [TestMethod]
+        [ExpectedException(typeof(System.ArgumentNullException))]
+        public void EvaluateExpresssion_RegexPatternNull_ArgumentNullExceptionIsThrown()
+        {
+            var regexOperator = new RegexOperator(null);
+            regexOperator.EvaluateExpression(TestUtilities.ToJToken("someValue"));
```
Comment (JohnathonMohr) [inline src/Analyzer.JsonRuleEngine.UnitTests/RegexOperatorTests.cs:70]: <minor> This line will never be hit.

**Review by JohnathonMohr — APPROVED** [review]
One test could use a minor change.
