### PR TITLE
Fix copy resources line number mapping bug

### LINKED ISSUE #125: ResolveLineNumber in the copy resources scenario does not account for the case where the expanded template resource name is not the same as the original template resource name
The expanded resource name can be different from the the original template resource name because the original resource name can refer to a parameter or variable, etc.

### PR DESCRIPTION
**Pull request by yane3628**
- Makes and uses mapping between resources in expanded template to original template for easier line number mapping (Closes #125)
- Processes all resources language expressions once flattened

### CODE REVIEW

File: src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs [hunk 1]
```diff
@@ -219,58 +235,98 @@ internal void CopyResourceDependants(TemplateResource templateResource, Dictiona
...
+        private void AddResourceMapping(string expandedTemplatePath, string originalTemplatePath)
+        {
+            // Save all permutations of the resource path based off values already present 
+            // in the dictionary with mapping. This is necessary to report an issue in
+            // a copied nth grandchild resource.
+            var tokens = expandedTemplatePath.Split('.');
+
+            for (int i = 0; i < tokens.Length - 1; i++)
+            {
+                string subPath = string.Join('.', tokens[..(i + 1)]);
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs:263]: Suggested name change: `potentialOriginalPathOfAnotherResource`?

File: src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs [hunk 2]
```diff
@@ -219,58 +235,98 @@ internal void CopyResourceDependants(TemplateResource templateResource, Dictiona
...
+                if (originalToExpandedMapping.ContainsKey(subPath))
+                {
+                    foreach (string path in originalToExpandedMapping[subPath])
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs:266]: Suggested name change: `copiedLocationOfAnotherResource`?

File: src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs [hunk 3]
```diff
@@ -219,58 +235,98 @@ internal void CopyResourceDependants(TemplateResource templateResource, Dictiona
...
+                    {
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs:267]: (With name changes):
``` suggestion
                if (originalToExpandedMapping.TryGetValue(potentialOriginalPathOfAnotherResource, out copiedLocationsOfAnotherResource))
                {
                    foreach (var copiedLocationOfAnotherResource in copiedLocationsOfAnotherResource)
                    {
```

File: src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs [hunk 4]
```diff
@@ -378,6 +426,12 @@ private TemplateResource[] ReorderResourceCopies(Template template, Dictionary<s
                         else if (!dropResourceCopies)
                         {
                             updatedOrder.Add(resource);
+                            resource.Path = $"resources[{updatedOrder.Count - 1}]";
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs:429]: I'm realizing now this will break if there are 2 or more resources with their own copy loops.  Both will be added to the end by the parsing and expansion, then reordering will add mappings for the copies of the first resource (below), then the second resource with a copy loop will be inserted into the array above (with `CopyIndex == 0`), pushing out the previous copies an extra index, making their previous mappings invalid.

**Review by JohnathonMohr — CHANGES_REQUESTED** [review]
Most are minor changes, but there's one bug that needs to be solved.

**Review by VeraBE — APPROVED** [review]

File: src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs [hunk 5]
```diff
@@ -240,6 +240,115 @@ public void ParseAndValidateTemplate_ValidTemplateWithExpressionInResourceProper
...
+            // First resource should be the resource without a copy index specified
+            Assert.AreEqual("resourceWith/NoCopyLoop", template.Resources.First().Name.Value);
+
+            Assert.AreEqual("name/SSH-VMNamePrefix-1", template.Resources[2].Name.Value);
+            Assert.AreEqual("[concat('name', '/', 'SSH-', 'VMNamePrefix-', copyIndex())]", template.Resources[2].OriginalName);
+            Assert.AreEqual(2201, template.Resources[2].Properties.Value.InsensitiveToken("frontendPort").Value<int>());
+
+            Assert.AreEqual("name/CopyLoop2-SSH-VMNamePrefix-1", template.Resources.Last().Name.Value);
+            Assert.AreEqual("[concat('name', '/', 'CopyLoop2-SSH-', 'VMNamePrefix-', copyIndex())]", template.Resources.Last().OriginalName);
+            Assert.AreEqual(2201, template.Resources.Last().Properties.Value.InsensitiveToken("frontendPort").Value<int>());
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs:347]: I don't think these assertions provide much value.  Since we have the path mapping between expanded and original templates (and that's all that's used), the order of the resources in the expanded template shouldn't matter in the end.

File: src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs [hunk 6]
```diff
@@ -418,13 +527,6 @@ public void CopyResourceDependants_ValidChildResourceDependsOnByNameAndResourceI
                 ""dependsOn"": [ ""someResource"" ],
                 ""properties"": { }
             }", DisplayName = "Child resource depends on resource outside template scope")]
-        [DataRow(@"{
-                ""type"": ""Microsoft.Network/networkInterfaces"",
-                ""apiVersion"": ""2018-10-01"",
-                ""name"": ""simpleLinuxVMNetInt"",
-                ""location"": ""westus"",
-                ""properties"": { }
-            }", DisplayName = "Child resource depends on not specified")]
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs:380]: Why was this test removed?

File: src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs [hunk 7]
```diff
@@ -392,58 +391,47 @@ private TemplateExpressionEvaluationHelper GetTemplateFunctionEvaluationHelper(T
...
-                            updatedOrder.Insert(originalValues.Item2, resource);
-                        }
-                        else if (!dropResourceCopies)
-                        {
-                            updatedOrder.Add(resource);
-                            resource.Path = $"resources[{updatedOrder.Count - 1}]";
-                        }
 
-                        if (!dropResourceCopies)
+                        if (!dropResourceCopies || resource.CopyContext.CopyIndex == 0)
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs:416]: I think we should remove the drop-copy logic.  I don't envision it being used.

File: src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs [hunk 8]
```diff
@@ -392,58 +391,47 @@ private TemplateExpressionEvaluationHelper GetTemplateFunctionEvaluationHelper(T
...
-                    updatedOrder.Add(resource);
-                }
-                else
-                {
-                    // Copied resource.  Update OriginalName and:
-                    // - if it's the first copy, insert back where it was supposed to be
-                    // - if it's an extra copy, add to the end, or don't add at all if requested
+                    // Copied resource.  Update OriginalName and
+                    // add maping to original resource
                     if (copyNameMap.TryGetValue(resource.Copy.Name.Value, out (string, int) originalValues))
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs:412]: This should have paired 'else' logic

File: src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs [hunk 9]
```diff
@@ -392,58 +391,47 @@ private TemplateExpressionEvaluationHelper GetTemplateFunctionEvaluationHelper(T
...
                             AddResourceMapping(resource.Path, $"resources[{originalValues.Item2}]");
                         }
-                    }
-                    else
-                    {
-                        // Couldn't get original values.  Insert at end as a precaution,
-                        // but this code should never be reached under normal circumstances.
-                        updatedOrder.Add(resource);
+
+                        continue;
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs:423]: It looks like this only skips one line of code.  That line should be moved into the 'else' block so `continue` can be removed.

File: src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs (hunk 7 above)
Comment (JohnathonMohr) [reply src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs:416]: Then this function doesn't have to return anything, it just maps.

File: src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs [hunk 10]
```diff
@@ -392,58 +391,47 @@ private TemplateExpressionEvaluationHelper GetTemplateFunctionEvaluationHelper(T
...
-                    // non-copied resource.  Add to updated array
-                    updatedOrder.Add(resource);
-                }
-                else
-                {
-                    // Copied resource.  Update OriginalName and:
-                    // - if it's the first copy, insert back where it was supposed to be
-                    // - if it's an extra copy, add to the end, or don't add at all if requested
+                    // Copied resource.  Update OriginalName and
+                    // add maping to original resource
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs:411]: minor: mapping

File: src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs [hunk 11]
```diff
@@ -131,7 +131,7 @@ internal Template ParseAndValidateTemplate(InsensitiveDictionary<JToken> paramet
                 // Do not throw if there was an issue with evaluating language expressions
             }
 
-            template.Resources = ReorderResourceCopies(template, copyNameMap);
+            template.Resources = MapResources(template, copyNameMap);
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs:134]: Since flatted (sub-) resources also have to be mapped later (line 164), should this method be named `MapTopLevelResources`?

File: src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs [hunk 12]
```diff
@@ -479,12 +582,14 @@ public void CopyResourceDependants_DependsOnIsSubResource_CopiesToCorrectResourc
...
                   ""properties"": { },
+                  ""dependsOn"": [ ],
                   ""resources"": [
                     {
                       ""apiVersion"": ""2015-08-01"",
                       ""name"": ""web"",
                       ""type"": ""sourcecontrols"",
-                      ""properties"": { }
+                      ""properties"": { },
+                      ""dependsOn"": [ ],
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs:592]: Why is an empty `"dependsOn"` array needed in so many resources?

File: src/Analyzer.Core/TemplateAnalyzer.cs [hunk 13]
```diff
@@ -44,11 +44,10 @@ public TemplateAnalyzer(string template, string parameters = null, string templa
         public IEnumerable<IEvaluation> EvaluateRulesAgainstTemplate()
         {
             JToken templatejObject;
-            ArmTemplateProcessor armTemplateProcessor;
+            var armTemplateProcessor = new ArmTemplateProcessor(Template);
 
             try
-            {
-                armTemplateProcessor = new ArmTemplateProcessor(Template);
+            {
```
Comment (JohnathonMohr) [inline src/Analyzer.Core/TemplateAnalyzer.cs:50]: minor: extra spaces after `{`

**Review by JohnathonMohr — CHANGES_REQUESTED** [review]

File: src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs (hunk 5 above)
Comment (yane3628) [reply src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs:347]: I can remove them and just leave the dictionary comparison.

File: src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs (hunk 6 above)
Comment (yane3628) [reply src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs:380]: I realized it wasn't necessary. I had to update the test to call a function higher in the stack. Once this happened, the resource objects all had an empty dependsOn added to them after processing.

Comment (JohnathonMohr) [reply src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs:380]: I guess I won't block on it, but I think the test still has value - it verifies this scenario is covered in the parsing.  The implementation depends on the ARM Deployment library setting a default empty array, but that's a detail that's abstracted from the test.  i.e. the test doesn't care *how* it's accounted for, just that it is in some way.

File: src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs (hunk 12 above)
Comment (yane3628) [reply src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs:592]: See my response in your other comment "Why was this test removed?"

File: src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs (hunk 6 above)
Comment (yane3628) [reply src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs:380]: It seemed like unnecessary work to add the expectation of dependsOn being added when comparing the json at the end of the test. That's why I removed the test instead of updating it.

File: src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs (hunk 12 above)
Comment (JohnathonMohr) [reply src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs:580]: It sounds like this property isn't actually necessary in the JSON then.  I guess I'm confused why it was added everywhere if it doesn't need to be specified.

File: src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs (hunk 6 above)
Comment (JohnathonMohr) [reply src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs:380]: Oh, now I see what's going on.

I get the desire to simplify the tests.  I think we should when we can.  In this case though, doesn't it seem like it's removing a test scenario in favor of simplifying the test?  Now it looks like the parsing library requires "dependsOn" to be specified.

File: src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs [hunk 14]
```diff
@@ -344,52 +388,36 @@ private TemplateExpressionEvaluationHelper GetTemplateFunctionEvaluationHelper(T
...
-                    updatedOrder.Add(resource);
-                }
-                else
-                {
-                    // Copied resource.  Update OriginalName and:
-                    // - if it's the first copy, insert back where it was supposed to be
-                    // - if it's an extra copy, add to the end, or don't add at all if requested
+                    // Copied resource.  Update OriginalName and
+                    // add mapping to original resource
                     if (copyNameMap.TryGetValue(resource.Copy.Name.Value, out (string, int) originalValues))
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs:406]: Combine this with the outer `if`

File: src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs [hunk 15]
```diff
@@ -344,52 +388,36 @@ private TemplateExpressionEvaluationHelper GetTemplateFunctionEvaluationHelper(T
...
+
+                        continue;
                     }
                 }
+                    
+                AddResourceMapping($"resources[{i}]", resource.Path);
             }
             
-            return updatedOrder.ToArray();
+            return;
```
Comment (JohnathonMohr) [inline src/Analyzer.TemplateProcessor/ArmTemplateProcessor.cs:420]: Unnecessary

File: src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs (hunk 6 above)
Comment (yane3628) [reply src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs]: Added the test back and updated the test

**Review by JohnathonMohr — APPROVED** [review]
