### PR TITLE
Fixes for issues #137 and #141

### LINKED ISSUE #137: Reduce duplication of code in AllOf and AnyOf expression classes and tests
There is opportunity to reduce code duplication in the following classes:
- src\Analyzer.JsonRuleEngine\Expressions\AllOfExpression.cs
- src\Analyzer.JsonRuleEngine\Expressions\AnyOfExpression.cs
- src\Analyzer.JsonRuleEngine.UnitTests\AllOfExpressionTests.cs
- src\Analyzer.JsonRuleEngine.UnitTests\AnyOfExpressionTests.cs

### LINKED ISSUE #141: When a resource is defined as a child resource and depends on is specified, CopyResourceDependants makes a second copy of the resource.
Update required in last else statement in CopyResourceDependants (at line 237) in ArmTemplateProcessor.cs. CopyResourceDependants should first check if the resource is already in the current resources array before copying.

Example:
``` javascript
"resources": [
    {
      "type": "Microsoft.Sql/servers",
      "apiVersion": "2020-02-02-preview",
      "name": "[parameters('sqlServerName')]",
      "location": "[parameters('location')]",
      "properties": {
        "administratorLogin": "[parameters('sqlAdministratorLogin')]",
        "administratorLoginPassword": "[parameters('sqlAdministratorPassword')]",
        "version": "12.0"
      },
      "resources": [
        {
          "type": "databases",
          "apiVersion": "2020-02-02-preview",
          "name": "[parameters('dataWarehouseName')]",
          "location": "[parameters('location')]",
          "kind": "v12.0,user,datawarehouse",
          "dependsOn": [
            "[parameters('sqlServerName')]"
          ],
          "properties": {
            "edition": "DataWarehouse",
            "status": "Online",
            "requestedServiceObjectiveName": "[parameters('serviceLevelObjective')]",
            "collation": "SQL_Latin1_General_CP1_CI_AS",
            "readScale": "Disabled",
            "zoneRedundant": false,
            "isUpgradeRequested": false
          },
          "resources": [
            {
              "comments": "Transparent Data Encryption",
              "type": "transparentDataEncryption",
              "apiVersion": "2017-03-01-preview",
              "name": "current",
              "dependsOn": [
                "[parameters('dataWarehouseName')]"
              ],
              "properties": {
                "status": "[parameters('transparentDataEncryption')]"
              }
            }
          ]
        }
      ]
    }
  ]
```

Results in
``` javascript
    "resources": [
      {
        "type": "Microsoft.Sql/servers",
        "apiVersion": "2020-02-02-preview",
        "name": "sqlhszmmda4ysaqy",
        "location": "westus2",
        "dependsOn": [],
        "properties": {
          "administratorLogin": "defaultString1",
          "administratorLoginPassword": "defaultString2",
          "version": "12.0"
        },
        "resources": [
          {
            "type": "databases",
            "apiVersion": "2020-02-02-preview",
            "name": "defaultString3",
            "location": "westus2",
            "dependsOn": [
              "sqlhszmmda4ysaqy"
            ],
            "kind": "v12.0,user,datawarehouse",
            "properties": {
              "edition": "DataWarehouse",
              "status": "Online",
              "requestedServiceObjectiveName": "DW400c",
              "collation": "SQL_Latin1_General_CP1_CI_AS",
              "readScale": "Disabled",
              "zoneRedundant": false,
              "isUpgradeRequested": false
            },
            "resources": [
              {
                "type": "transparentDataEncryption",
                "apiVersion": "2017-03-01-preview",
                "name": "current",
                "comments": "Transparent Data Encryption",
                "dependsOn": [
                  "defaultString3"
                ],
                "properties": {
                  "status": "Disabled"
                }
              }
            ]
          },
          {
            "type": "databases",
            "apiVersion": "2020-02-02-preview",
            "name": "defaultString3",
            "location": "westus2",
            "dependsOn": [
              "sqlhszmmda4ysaqy"
            ],
            "kind": "v12.0,user,datawarehouse",
            "properties": {
              "edition": "DataWarehouse",
              "status": "Online",
              "requestedServiceObjectiveName": "DW400c",
              "collation": "SQL_Latin1_General_CP1_CI_AS",
              "readScale": "Disabled",
              "zoneRedundant": false,
              "isUpgradeRequested": false
            },
            "resources": [
              {
                "type": "transparentDataEncryption",
                "apiVersion": "2017-03-01-preview",
                "name": "current",
                "comments": "Transparent Data Encryption",
                "dependsOn": [
                  "defaultString3"
                ],
                "properties": {
                  "status": "Disabled"
                }
              }
            ]
          }
        ]
```

### PR DESCRIPTION
**Pull request by nonik0**
Fixes for issues:
Closes #137
Closes #141

### CODE REVIEW

**Comment by yane3628** [comment]
@nonik0 Looks like some tests are failing.

**Comment by nonik0** [comment]
> @nonik0 Looks like some tests are failing.

Yeah I lterally ran all the test before submitted and they passed, but I ran again and I see the issue. Working on it.

File: src/Analyzer.JsonRuleEngine/Expressions/AnyOfExpression.cs [hunk 1]
```diff
@@ -1,58 +1,30 @@
...
 
-using System;
-using System.Collections.Generic;
-using Microsoft.Azure.Templates.Analyzer.Types;
-
 namespace Microsoft.Azure.Templates.Analyzer.RuleEngines.JsonEngine.Expressions
 {
     /// <summary>
-    /// Represents an anyOf expression in a JSON rule.
+    /// Represents an allOf expression in a JSON rule.
```
Comment (yane3628) [inline src/Analyzer.JsonRuleEngine/Expressions/AnyOfExpression.cs:7]: *anyOf

File: src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+// Licensed under the MIT License.
+
+using System;
+using System.Collections.Generic;
+using Microsoft.Azure.Templates.Analyzer.Types;
+
+namespace Microsoft.Azure.Templates.Analyzer.RuleEngines.JsonEngine.Expressions
+{
+    /// <summary>
+    /// Represents an anyOf expression in a JSON rule.
```
Comment (yane3628) [inline src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs:11]: Update comment

File: src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+        /// </summary>
+        internal LogicalOperator Operator;
+
+        /// <summary>
+        /// Gets or sets the expressions to be evaluated.
+        /// </summary>
+        internal Expression[] Expressions { get; set; }
+
+        /// <summary>
+        /// Creates an <see cref="LogicalExpression"/>.
```
Comment (yane3628) [inline src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs:35]: *a

File: src/Analyzer.JsonRuleEngine/Expressions/AllOfExpression.cs [hunk 4]
```diff
@@ -1,59 +1,30 @@
...
-using System.Collections.Generic;
-using Microsoft.Azure.Templates.Analyzer.Types;
-
 namespace Microsoft.Azure.Templates.Analyzer.RuleEngines.JsonEngine.Expressions
 {
     /// <summary>
     /// Represents an allOf expression in a JSON rule.
     /// </summary>
-    internal class AllOfExpression : Expression
+    internal class AllOfExpression : LogicalExpression
```
Comment (yane3628) [inline src/Analyzer.JsonRuleEngine/Expressions/AllOfExpression.cs:9]: There's also some duplication of code in the test files for AllOfExpression and AnyOfExpression. These likely can be simplified greatly since AllOfExpression has been simplified so much, so maybe the shared code just make it a new test file for LogicalExpression.

File: src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs [hunk 5]
```diff
@@ -665,6 +665,82 @@ public void CopyResourceDependants_DependsOnIsSubResource_CopiesToCorrectResourc
...
+        [TestMethod]
+        public void CopyResourceDependants_DependsOnSpecifiedInNestedChildResource()
+        {
+            // Arrange
+            string resourceJson = @"{
+                ""type"": ""Microsoft.Sql/servers"",
+                ""apiVersion"": ""2020-02-02-preview"",
+                ""name"": ""sqlServerName"",
+                ""location"": ""location"",
+                ""properties"": {
```
Comment (yane3628) [inline src/Analyzer.TemplateProcessor.UnitTests/ArmTemplateProcessorTests.cs:677]: Optional: To reduce the number of lines in this test, you can make all the `properties` sections empty objects. They're not important for this test.

**Review by yane3628 — CHANGES_REQUESTED** [review]

File: src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs [hunk 6]
```diff
@@ -0,0 +1,87 @@
...
+                bool evaluationPassed = Operator != LogicalOperator.Or;
+
+                foreach (var expression in Expressions)
+                {
+                    var evaluation = expression.Evaluate(scope);
+
+                    // Add evaluations if scopes were found to evaluate
+                    if (evaluation.HasResults)
+                    {
+                        switch (Operator)
```
Comment (VeraBE) [inline src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs:67]: Maybe it makes sense to receive in the constructor an Action that is then called here instead of storing information for each operator in the class members and doing a switch here?

File: src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs [hunk 7]
```diff
@@ -0,0 +1,87 @@
...
+using System;
+using System.Collections.Generic;
+using Microsoft.Azure.Templates.Analyzer.Types;
+
+namespace Microsoft.Azure.Templates.Analyzer.RuleEngines.JsonEngine.Expressions
+{
+    /// <summary>
+    /// Represents an anyOf expression in a JSON rule.
+    /// </summary>
+    internal class LogicalExpression : Expression
```
Comment (VeraBE) [inline src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs:13]: I found the name a little confusing because most of the expressions in a way represent a logical property, right? Maybe it makes sense for this class to abstract list-based structured operators?

File: src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs (hunk 6 above)
Comment (nonik0) [reply src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs:67]: I like this idea.

File: src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs (hunk 7 above)
Comment (nonik0) [reply src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs:13]: Yeah that makes sense, I'll work on that.

Comment (nonik0) [reply src/Analyzer.JsonRuleEngine/Expressions/LogicalExpression.cs:13]: FYI, I was thinking logical [in this sense](https://www.sciencedirect.com/topics/engineering/logical-expression#:~:text=A%20logical%20expression%20is%20a,and%200%20to%20indicate%20false.) but maybe that's more of a "math" term. I like the list-based idea still.

File: src/Analyzer.JsonRuleEngine/Expressions/AllOfExpression.cs (hunk 4 above)
Comment (nonik0) [reply src/Analyzer.JsonRuleEngine/Expressions/AllOfExpression.cs:9]: Good idea, will do.

**Review by VeraBE — APPROVED** [review]

File: src/Analyzer.JsonRuleEngine/Expressions/AllOfExpression.cs [hunk 8]
```diff
@@ -1,59 +1,30 @@
...
-using System.Collections.Generic;
-using Microsoft.Azure.Templates.Analyzer.Types;
-
 namespace Microsoft.Azure.Templates.Analyzer.RuleEngines.JsonEngine.Expressions
 {
     /// <summary>
     /// Represents an allOf expression in a JSON rule.
     /// </summary>
-    internal class AllOfExpression : Expression
+    internal class AllOfExpression : CompoundExpression
```
Comment (yane3628) [inline src/Analyzer.JsonRuleEngine/Expressions/AllOfExpression.cs:9]: In the docs we refer to allOf and anyOf as Structured Expressions. Should we change this to that same term here? @VeraBE and @JohnathonMohr

File: src/Analyzer.JsonRuleEngine/Expressions/CompoundExpression.cs [hunk 9]
```diff
@@ -0,0 +1,78 @@
...
+        /// <summary>
+        /// Gets or sets the expressions to be evaluated.
+        /// </summary>
+        internal Expression[] Expressions { get; set; }
+
+        /// <summary>
+        /// Creates a <see cref="CompoundExpression"/>.
+        /// </summary>
+        /// <param name="expressions">List of expressions to perform a logical operation against.</param>
+        /// <param name="operation">The boolean operation to perform to compound the expressions results</param>
```
Comment (yane3628) [inline src/Analyzer.JsonRuleEngine/Expressions/CompoundExpression.cs:29]: Minor: Missing period at the end of sentence.

**Review by yane3628 — APPROVED** [review]
Small (non-blocking) comments

File: src/Analyzer.JsonRuleEngine/Expressions/AllOfExpression.cs (hunk 8 above)
Comment (VeraBE) [reply src/Analyzer.JsonRuleEngine/Expressions/AllOfExpression.cs:9]: I was thinking of something like StructuredListExpression, but I'm okay with either

Comment (nonik0) [reply src/Analyzer.JsonRuleEngine/Expressions/AllOfExpression.cs:9]: Yeah I was going to ask about the name, happy to change all references to StructuredListExpression.

Comment (nonik0) [reply src/Analyzer.JsonRuleEngine/Expressions/AllOfExpression.cs]: Ended up using StructuredExpression when doing the changes.
